apiVersion: apps/v1
kind: Deployment
metadata:
  name: iprwc-deployment
  namespace: iprwc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iprwc
  template:
    metadata:
      labels:
        app: iprwc
    spec:
      imagePullSecrets:
        - name: ghcr-access-token
      containers:
        - name: api
          image: ghcr.io/wesleyklop/iprwc-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database-url
                  name: iprwc-credentials
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt-secret
                  name: iprwc-credentials
            - name: MAILER_URL
              valueFrom:
                secretKeyRef:
                  key: mail-url
                  name: iprwc-credentials
            - name: MAILER_FROM
              value: noreply@iprwc.wesl.io
            - name: APP_URL
              value: https://iprwc.wesl.io
          volumeMounts:
            - mountPath: /srv/iprwc-backend/static
              name: static
        - name: web
          image: ghcr.io/wesleyklop/iprwc-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: iprwc-static
